config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :groups
  devise_for :users
  root 'home#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
    class Ability
      include CanCan::Ability
      def initialize(user)
        if user.admin?
          can :manage, :all
        else
          can [:read, :update, :destroy], Car
          can :manage, User
        end
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/memberable.rb
module Memberable
  extend ActiveSupport::Concern
  included do
    has_many :memberships, as: :memberable, dependent: :destroy
    has_many :users, through: :memberships
    after_create :create_membership
  end

  def create_membership
    Membership.create(memberable_type: self.class.name, memberable_id: self.id, user_id: self.creator_id)
  end
end

app/models/group.rb
class Group < ApplicationRecord
  include Memberable
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :memberable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memberships
  has_many :groups, through: :memberships, source: :memberable, source_type: 'Group'
  has_many :projects, through: :memberships, source: :memberable, source_type: 'Project'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to '/', :alert => exception.message
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.creator_id = current_user.id
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @groups = current_user.groups
    @users = User.all
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:memberable_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<h4>Menbros</h4>
<p>
  <% @group.memberships.each do |member| %>
  <%= member.user.email %>
  <% end %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/home/index.html.erb
<!--=============================== Header ===========================-->
<div id="header"></div>

<!--=============================== Menu-Bar ========================-->
<div id="menuBar-charity"></div>

<!--=============================== Slider ==========================-->
<div class="slider">
  <div id="home-carousel" class="carousel" data-ride="carousel">
    <div class="carousel-inner" role="listbox">

      <div class="item active slide_1">
        <div class="container p0">
          <div class="item-content">
            <div class="gb-middle ">
              <div class="slider-info ">
                <h4>Junte-se ao Ajudanto Juntos</h4>
                <h2>Ajude Pessoas Idosas</h2>
                <div class="buttons">
                  <a href="features.html" class="red-btn red-btn-0">How You Can Help?</a>
                </div>
              </div>
            </div>
          </div><!-- /.item-content -->
        </div>
      </div><!-- /.item -->

      <div class="item slide_2 ">
        <div class="container p0">
          <div class="item-content">
            <div class="gb-middle">
              <div class="slider-info">
                <h4>Junte-se ao Ajudanto Juntos</h4>
                <h2>Ajude a colocar um sorriso no rosto</h2>
                <div class="buttons">
                  <a href="features.html" class="red-btn red-btn-0">How You Can Help?</a>
                </div>
              </div>
            </div>
          </div><!-- /.item-content -->
        </div>
      </div><!-- /.item -->

      <div class="item slide_3 ">
        <div class="container p0">
          <div class="item-content">
            <div class="gb-middle">
              <div class="slider-info">
                <h4>Junte-se ao Ajudanto Juntos</h4>
                <h2>Ajude no futuro de todos</h2>
                <div class="buttons">
                  <a href="features.html" class="red-btn red-btn-0">How You Can Help?</a>
                </div>
              </div>
            </div>
          </div><!-- /.item-content -->
        </div>
      </div><!-- /.item -->

    </div><!-- /.carousel-inner -->

    <ol class="carousel-indicators">
      <li data-target="#home-carousel" data-slide-to="0" class="active"></li>
      <li class="two" data-target="#home-carousel" data-slide-to="1"></li>
      <li data-target="#home-carousel" data-slide-to="2"></li>
    </ol>

  </div><!-- /.carousel slide -->
</div><!-- /.slider -->


<!--=============================== Images ==========================-->
<div class="main-container-2 grey">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-4 col-xs-12 text-center mb">
        <div class="images">
          <p> <%=image_tag "drop.png"%></p>
        </div>
        <div class="images-text">
          <h2><a href="single-causes.html">Donation</a></h2>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 text-center mb">
        <div class="images">
          <p> <%=image_tag "circle.png"%></p>
        </div>
        <div class="images-text">
          <h2><a href="features.html">Get Involved</a></h2>
        </div>
      </div>
      <div class="col-md-4 col-sm-4 col-xs-12 text-center">
        <div class="images">
          <p> <%=image_tag "heart.png"%></p>
        </div>
        <div class="images-text">
          <h2><a href="login.html">Join Us</a></h2>
        </div>
      </div>
    </div>
  </div>
</div>



<!--=============================== Number ======================-->
<div class="number" id="counts">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12 mb center ">
        <div class="text">
          <p>
            <span class="spincrement">500</span>
            <span class="text-1"> Successful Projects </span>
          </p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 mb center ">
        <div class="text">
          <p>
            <span class="spincrement">1534</span>
            <span class="text-1"> People Impacted </span>
          </p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 mb center ">
        <div class="text">
          <p>$
            <span class="spincrement ml">14432</span>
            <span class="text-1"> Money Donated </span>
          </p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6 col-xs-12 center ">
        <div class="text">
          <p><span class="spincrement">189</span>
            <span class="text-1"> Total Volunteers </span>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<!--=============================== Our Causes ======================-->
<div class="main-container-4">
  <div class="container">

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="text-center">
          <h2 class="title-text">Nossas Causas</h2>
          <div class="wave-line wave-center"></div>
          <p class="paragraph-white">Fundraising event ideas have become a staple in many organizations
            as a way to help with fundraising event planning, entertaining and engaging your donors </p>
        </div>
      </div>
    </div>

    <div class="row">

      <div class="col-lg-4 col-md-4 col-sm-6 mb">
        <div class="person-card ">
          <div class="person-img">
            <a href="our-causes.html" class="img-link">
              <span><i class="icon-eye" aria-hidden="true"></i></span>
              <img src="http://via.placeholder.com/370x300" alt="" class="img">
            </a>
          </div>
          <div class="person-content">
            <h3><a href="our-causes.html" class="title-white">Provide Treatment</a></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut labore et. </p>
          </div>
        </div>
        <div class="scale-area">
          <h6>Raised</h6>
          <h6 class="pull-right">Goal</h6>
          <div class="scale clearfix">
            <div class="scale-bar-1" data-percent="43"></div>
            <div class="scale-bar-percent">43%</div>
          </div>
          <h6>5730.00 USD</h6>
          <h6 class="pull-right">112000.00 USD</h6>
        </div>
        <div class="buttons">
          <a href="single-causes.html" class=" red-btn red-btn-4">Donate</a>
        </div>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-6 mb">
        <div class="person-card ">
          <div class="person-img">
            <a href="our-causes.html" class="img-link">
              <span><i class="icon-eye" aria-hidden="true"></i></span>
              <img src="http://via.placeholder.com/370x300" alt="" class="img">
            </a>
          </div>
          <div class="person-content">
            <h3><a href="our-causes.html" class="title-white">Education to Every Child</a></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut labore et. </p>
          </div>
        </div>
        <div class="scale-area">
          <h6>Raised</h6>
          <h6 class="pull-right">Goal</h6>
          <div class="scale clearfix">
            <div class="scale-bar-1" data-percent="87"></div>
            <div class="scale-bar-percent">87%</div>
          </div>
          <h6>5730.00 USD</h6>
          <h6 class="pull-right">112000.00 USD</h6>
        </div>
        <div class="buttons">
          <a href="single-causes.html" class=" red-btn red-btn-4">Donate</a>
        </div>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-6">
        <div class="person-card ">
          <div class="person-img">
            <a href="our-causes.html" class="img-link">
              <span><i class="icon-eye" aria-hidden="true"></i></span>
              <img src="http://via.placeholder.com/370x300" alt="" class="img">
            </a>
          </div>
          <div class="person-content">
            <h3><a href="our-causes.html" class="title-white">Patient and Family Support</a></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut labore et. </p>
          </div>
        </div>
        <div class="scale-area">
          <h6>Raised</h6>
          <h6 class="pull-right">Goal</h6>

          <div class="scale clearfix">
            <div class="scale-bar-1 stop" data-percent="62"></div>
            <div class="scale-bar-percent">62%</div>
          </div>
          <h6>5730.00 USD</h6>
          <h6 class="pull-right">112000.00 USD</h6>
        </div>
        <div class="buttons">
          <a href="single-causes.html" class=" red-btn red-btn-4">Donate</a>
        </div>
      </div>
    </div>
  </div>
</div>



<!--=============================== Footer ===========================-->
<div id="footer"></div>

</div>  <!--  /.page -->


<!-- JS code -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="assets/js/jquery.spincrement.js"></script>
<script src="assets/js/owl.carousel.min.js"></script>
<script src="assets/js/scrollBar.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/myScript.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>HelpingTogether</title>
  <meta charset="UTF-8">
  <title>THX - Charity HTML Template | Homepage</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <!-- Google fonts Poppins -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Fontello -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="assets/js/respond.min.js"></script>

  <![endif]-->
</head>
<body>
<div class="page">
  <%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</body>
</html>

app/views/memberships/_form.html.erb
<%= form_with(model: membership, local: true) do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :memberable_id %>
    <%= form.select :memberable_id, @groups.collect { |group| [group.name, group.id] }  %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, @users.collect { |user| [user.email, user.id] }  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Memberable</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.memberable_id %></td>
        <td><%= membership.user_id %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Memberable:</strong>
  <%= @membership.memberable_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @membership.user_id %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>